version: '2'
services:
    senpaie-app:
        image: senpaie
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://senpaie-postgresql:5432/senPaie
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    senpaie-postgresql:
        extends:
            file: postgresql.yml
            service: senpaie-postgresql
